from typing import Any, Dict
from langgraph.prebuilt import ToolNode
from langgraph.graph import StateGraph, END
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("dummy-agent-3")


class AgentThree:
    def __init__(self, name: str = "agent3") -> None:
        self.name = name

    def build_graph(self):
        workflow = StateGraph(dict)
        workflow.add_node("plan", self.plan)
        workflow.add_node("execute", ToolNode([]))
        workflow.add_edge("plan", "execute")
        workflow.add_edge("execute", END)
        return workflow.compile()

    def plan(self, state: Dict[str, Any]) -> Dict[str, Any]:
        return {**state, "plan": "dummy execution plan"}

    def run(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        return {"agent": self.name, "status": "placeholder", "payload": payload}


@mcp.tool()
def generate_stub() -> Dict[str, Any]:
    return {"message": "stub generated by agent3"}
